package testsale

import "context"

// TestingTB abstracts the subset of testing.TB methods used by test helpers.
//
//go:generate mockgen -source interfaces.go -destination=./testing_t_mock_autogenerated.go -package=testsale
type TestingTB interface {
	Helper()
	Cleanup(func())
	Error(args ...interface{})
	Errorf(format string, args ...interface{})
	Fail()
	FailNow()
	Failed() bool
	Fatal(args ...interface{})
	Fatalf(format string, args ...interface{})
	Log(args ...interface{})
	Logf(format string, args ...interface{})
	Name() string
	Skip(args ...interface{})
	SkipNow()
	Skipf(format string, args ...interface{})
	Skipped() bool
	TempDir() string
	Setenv(key, value string)
	Chdir(dir string)
	Context() context.Context
}
