// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source interfaces.go -destination=./mocks_test.go -package=pdfcardsummaryio
//

// Package pdfcardsummaryio is a generated GoMock package.
package pdfcardsummaryio

import (
	reflect "reflect"

	pdfcardsummary "github.com/Alechan/finance-analyzer/pkg/internal/pdfcardsummary"
	pdfwrapper "github.com/Alechan/finance-analyzer/pkg/internal/platform/pdfwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
	isgomock struct{}
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// ExtractFromBytes mocks base method.
func (m *MockExtractor) ExtractFromBytes(rawBytes []byte) (pdfcardsummary.CardSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFromBytes", rawBytes)
	ret0, _ := ret[0].(pdfcardsummary.CardSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFromBytes indicates an expected call of ExtractFromBytes.
func (mr *MockExtractorMockRecorder) ExtractFromBytes(rawBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFromBytes", reflect.TypeOf((*MockExtractor)(nil).ExtractFromBytes), rawBytes)
}

// ExtractFromDocument mocks base method.
func (m *MockExtractor) ExtractFromDocument(pdfDoc pdfwrapper.Document) (pdfcardsummary.CardSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFromDocument", pdfDoc)
	ret0, _ := ret[0].(pdfcardsummary.CardSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFromDocument indicates an expected call of ExtractFromDocument.
func (mr *MockExtractorMockRecorder) ExtractFromDocument(pdfDoc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFromDocument", reflect.TypeOf((*MockExtractor)(nil).ExtractFromDocument), pdfDoc)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidator) Validate(cs pdfcardsummary.CardSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), cs)
}
